export const JSON_FILE_NAME = 'version-web-update-notify'
export const INJECT_STYLE_FILE_NAME = 'plugin-web-update-notify'
export const INJECT_SCRIPT_FILE_NAME = 'plugin-web-update-notify'
export const CUSTOM_UPDATE_EVENT_NAME = 'webupdatenotify'
export const NOTIFY_CLASS_NAME = 'plugin-web-update-notify'
